# Generated by Django 5.1.6 on 2025-02-07 06:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(error_messages={'invalid': 'Enter a valid 10-digit phone number starting with 7, 8, or 9.'}, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must start with 7, 8 or 9 and be 10 digits long.', regex='^[789]\\d{9}$')]),
        ),
    ]
