# Generated by Django 5.1.6 on 2025-02-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovidercertification',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovidercertification',
            name='issuing_authority',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
